version: '3.5'

services:
  webserver-0:
    container_name: myweb-0
    image: mywebserver:1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./html_file:/var/www/html
    ports:
      - "40:80"
    command : |
      bash -c "
        service apache2 start
        tail -f /dev/null
      "

  webserver-1:
    container_name: myweb-1
    image: mywebserver:1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./html_file:/var/www/html
    ports:
      - "50:80"
    command : |
      bash -c "
        service apache2 start
        tail -f /dev/null
      "

